# SPDX-FileCopyrightText: 2025 diggsweden/wallet-backend-reference
#
# SPDX-License-Identifier: EUPL-1.2

spring:
  application:
    name: demo
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    role: postgres
    user: postgres
    password: test
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

