# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

name: OpenSSF Scorecard Analysis
on:
  schedule:
    # Saturdays at 02:30 UTC
    - cron: "30 2 * * 6"
    # Wednesdays at 02:30 UTC
    - cron: "30 2 * * 3"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scorecard-analysis:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: diggsweden/reusable-ci/.github/workflows/security-openssf-scorecard.yml@cd56d63b88cf6f1ebb4dc3431986f4208ab85fc5 # v2.8.1
    with:
      publish-results: true
